config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/dashboard'
  # Read all
  # get 'cars', to: 'cars#index'
  # get '/cars/new', to: 'cars#new'
  # post '/cars', to: 'cars#create'

  # # Read one - The `show` route needs to be *after* `new` route.
  # get 'cars/:id', to: "cars#show", as: :car

  # get 'cars/:id/edit', to: "cars#edit"
  # patch 'cars/:id', to: 'cars#update'

  # delete "cars/:id", to: "cars#destroy"

  devise_for :users
  root to: "pages#home"
  get 'dashboards', to: 'dashboards#dashboard'
  resources :cars, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :update]
  end
  resources :bookings, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :start_rent, :end_rent, presence: true
  enum status: { pending: 0, accepted: 1, declined: 2 }
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings
  has_many :reviews
  belongs_to :user
  has_one_attached :photo
  validates :brand_name, :price, :city, :seats, presence: true

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :reviews
  has_many :cars
  # Les voitures que j'ai loué
  has_many :rented_cars, through: :bookings, source: :car, dependent: :destroy
  # Les voitures que j'ai reviews
  has_many :reviewed_cars, through: :reviews, source: :car
  # Les voitures que l'on m'a loué
  has_many :requested_cars, through: :cars, source: :bookings

  #profile picture de l'utilisateur
  has_one_attached :photo

  validates :name, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.car = Car.find(params[:car_id])
    @booking.user = current_user
    if @booking.save
      flash.alert = "Your booking is ok!"
      redirect_to dashboards_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def update
    @booking = Booking.find(params[:id])
    params[:booking][:status] = params[:booking][:status].to_i if params[:booking][:status].present?
    @booking.update(booking_params)
    if booking_params[:status].present?
      redirect_to dashboards_path

    else
      redirect_to car_path(@booking)
    end

  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:start_rent, :end_rent, :message, :status, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @cars = Car.all
    @user = current_user
    if params[:query].present?
      sql_query = "brand_name ILIKE :query OR city ILIKE :query"
      @cars = Car.where(sql_query, query: "%#{params[:query]}%")
    else
      @cars = Car.all
    end
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: {car: car})
      }
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @user = current_user
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to dashboards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path, status: :see_other
  end


  private

  def car_params
    params.require(:car).permit(:brand_name, :model, :city, :seats, :price, :overview, :user_id, :photo)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @user = current_user
    @cars = @user.cars
    @car = Car.new
    @past_bookings = @user.bookings.select {|booking| booking.end_rent < Date.today && booking.request == false}
    @current_bookings = @user.bookings.select {|booking| booking.start_rent == Date.today && booking.request == false}
    @future_bookings = @user.bookings.select {|booking| booking.start_rent > Date.today  && booking.request == false}
    @pending_requests = @user.requested_cars.pending
    @accepted_requests = @user.requested_cars.accepted
    @declined_requests = @user.requested_cars.declined
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cars = Car.all
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_car_card.html.erb
<div class="card-product">
  <%= cl_image_tag(car.photo.key) %>
  <div class="card-product-infos p-3 d-flex justify-content-between align-items-center w-100">
    <div>
      <h2><%= car.brand_name %></h2>
      <p class="m-0"><%= booking.start_rent %> | <%= booking.end_rent %></p>
    </div>
    <div class="notification-actions d-flex">
      <%=link_to "✏️", car_path(car), class:"me-2" %>
      <%=link_to "🗑", booking_path(booking),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </div>
  </div>
</div>


<%# ,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/cars/_info_window.html.erb
<div>
  <%= cl_image_tag car.photo.key, class:"card-img-top", alt:"car" %>
  <h2><%=link_to car.brand_name, car_path(car.id) %></h2>
  <p><%= car.city %></p>
</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/index.html.erb
<h1 class= "text-center mt-4 mb-4"><strong>Choose your dream car !</strong></h1>

<div class="container mb-4 w-50">
    <%= form_with url: cars_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control me-3", placeholder: "Find the car of your dreams" %>
      <%= submit_tag "Search", class: "btn btn-primary btn-search" %>
    <% end %>
</div>

<div class="main-container">
  <div class="cards-index">
    <% @cars.each do |car|%>
      <div class="card-trip">
        <%= cl_image_tag car.photo.key, class:"card-img-top", alt:"car" %>
        <%# <%= image_tag car.picture %>
        <div class="card-trip-infos" id="card-index">
          <div class="card-trip-infos-top">
            <h2><%=car.brand_name%></h2>
            <div>
              <ul>
                <li><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i></li>
              </ul>
            </div>
          </div>

          <p class="card-text text-ellipsis--2"> <%=car.overview%></p>

          <a href="<%= car_path(car.id) %>" class="btn btn-primary w-100 mt-3">Rent for <strong><%=car.price%>€</strong>/day</a>
        </div>
      </div>
    <% end%>


  </div>
    <div id="the-map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/cars/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-8">

      <div class="card-trip-infos-top">
        <div class="mb-2">
          <h1><%=@car.brand_name%></h1>
        </div>
        <div>
          <ul>
            <li><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i></li>
          </ul>
        </div>
      </div>

      <div class="card-trip">
        <%= cl_image_tag @car.photo.key, class:"card-img-top", alt:"car" %>
        <%# <%= image_tag car.picture %>
      </div>

      <div class="card-trip-infos mt-4">
        <div class= "description mt-3 d-flex justify-content-between">
        <p>Description</p>
        <p><%= @car.city%></p>
        </div>

        <p class="card-text text-muted"> <%=@car.overview%></p>
        <div style="margin-bottom: 50px;">
          <a href="<%= cars_path %>" >Back to the cars</a>
        </div>
      </div>
    </div>

    <div class="form col-sm-4 mt-2 sticky">
      <h2><%= @car.price %> € / per day </h2>
      <div data-controller="flatpickr">
        <%= simple_form_for [@car, @booking],
                            html: {
                              data: {
                                controller: 'flatpickr'
                              }
                            } do |f| %>
                            <div class="d-flex flex-column">
          <%= f.input :start_rent,
                      label: 'From:',
                      as: :string,
                      # label: 'Start - End',
                      input_html: {
                        data: {
                          flatpickr_target: 'startDateInput',
                        }
                      } %>
          <%= f.input :end_rent,
                      label: 'To:',
                      as: :string,
                      # wrapper_html: { class: 'd-none' },
                      input_html: {
                        data: {
                          flatpickr_target: 'endDateInput',
                        }
                      } %>
          <%= f.input :message  %>
          <%= f.submit 'Book now!', class: 'btn btn-primary align-self-center' %>
                          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/dashboards/_requests.html.erb
<div class="card-product">
  <% if request.user.photo.key %>
   <%= cl_image_tag request.user.photo.key %>
  <% else %>
    <%= image_tag "profile.jpg"%>
  <% end %>
  <div class="card-product-infos p-3 d-flex justify-content-between align-items-center w-100">
    <div>
      <h5 class="m-0"><%= request.user.name %></h5>
      <p class="m-0"><%= request.start_rent %> | <%= request.end_rent %></p>
      <p><em>"<%= request.message %></em>"</p>
    </div>
    <%# <h5><%= request.status %></h5>
    <%#= car.overview %>
    <% if request.pending? %>
      <div class="notification-actions d-flex">
        <%=link_to "✅",  car_booking_path(request.car, request, booking: {status: 1}), data: { turbo_method: :patch }, class:"me-2" %>
        <%=link_to "❌",  car_booking_path(request.car, request, booking: {status: 2}), data: { turbo_method: :patch } %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/dashboard.html.erb
<div class="container" >
  <div class="row my-5">
      <div class="d-flex justify-content-top pb-5 align-items-center">
        <h1 class="ps-3">Hello <%= current_user.name %></h2>
      </div>
    <div class="px-4 col-4">
      <div>
        <h2>Your cars</h2>
        <h6>You have <span class="title"> <%= @cars.length %> </span> in your garage</h6>
          <% @cars.each do |car| %>
            <div class="card-product">
              <%= cl_image_tag car.photo.key, class:"car-photo"%>
              <div class="card-product-infos p-3">
                <h2>
                  <%= car.brand_name %>
                </h2>
               <h2><%= car.price %> €</h2>
              </div>
            </div>
          <% end %>

          <!-- Button trigger modal -->
          <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Rent your car
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">My car</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for @car do |f| %>
                  <div class="form-inputs">
                    <%= f.input :brand_name %>
                    <%= f.input :seats %>
                    <%= f.input :city %>
                    <%= f.input :overview %>
                    <%= f.input :price %>
                    <%= f.input :photo, as: :file %>
                  </div>
                  <div class="form-actions">
                  <%= f.button :submit, "Create", class: "btn btn-dark w-100 rounded"%>
                  </div>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <%# <button type="button" class="btn btn-primary">Save changes</button> %>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>

    <div class="px-4 col-4 border-end border-start border-dark border-1">
      <div>
          <h2>Your bookings</h2>

            <h6 class="title" >Pending</h6>
            <% @current_bookings.each do |booking| %>
              <%= render 'cars/car_card', car: booking.car, booking: booking %>
            <% end %>


            <h6 class="title1">Coming</h6>
            <% @future_bookings.each do |booking| %>
              <%= render 'cars/car_card', car: booking.car, booking: booking %>
            <% end %>


             <h6 class="title2">Past</h6>
             <% @past_bookings.each do |booking| %>
                    <%= render 'cars/car_card', car: booking.car, booking: booking %>
             <% end %>
        </div>
    </div>

    <div class="px-4 col-4" >

      <h2>Your requests</h2>
      <h6 class= "title">Pending</h6>
      <% @pending_requests.each do |request| %>
        <%= render 'requests', request: request %>
      <% end %>
      <h6 class= "title1">Accepted</h6>
      <% @accepted_requests.each do |request| %>
        <%= render 'requests', request: request %>
      <% end %>
      <h6 class= "title2">Declined</h6>
      <% @declined_requests.each do |request| %>
        <%= render 'requests', request: request %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OldTheRoad</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap">
  </head>

  <body>
      <%= render "shared/navbar" %>
    <div class="wrapper">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
      <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgb(0 0 0 / 56%), rgba(0,0,0,0.3)), url(https://source.unsplash.com/UxXXow9095I.jpg)">
  <div class="container w-50">
    <h1><strong><span data-controller="typed-js"></span></strong></h1>
    <%# <p><em>Rent the car of your dreams</em></p> %>
    <%= form_with url: cars_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control me-3 w-75", placeholder: "Find the car of your dreams" %>
      <%= submit_tag "Search", class: "btn btn-primary btn-search" %>
    <% end %>
  </div>
</div>

<div class="container mb-5">
  <h3> Our favorite rented cars </h3>
  <div class="cards">

 <% @cars.sample(3).each do |car|%>
    <div class="card-trip">
      <%= cl_image_tag car.photo.key, class:"card-img-top", alt:"car" %>
        <div class="card-trip-infos">
          <div class="card-trip-infos-top">
            <div>
            <h2><%=car.brand_name%></h2>
            </div>
            <div class="justify-content-end">
              <ul>
                <li><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i><i class="fa-solid fa-star mt-3"></i></li>
              </ul>
            </div>
          </div>
          <p class="card-text text-ellipsis--2"> <%=car.overview%></p>
          <a href="<%= car_path(car) %>" class="btn btn-primary w-100 mt-3">Rent for <strong><%=car.price%>€</strong>/day</a>
        </div>
      </div>
    <% end%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a class="nav-link" href="#">Subscribe</a>
  </div>
  <div class="footer-copyright">
    Old the road <i class="fas fa-heart"></i> 2022
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", width: "200px", class: 'logo' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <%= link_to "Our Cars", cars_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <%# <li class="nav-item active">
          <%# </li> %>
          <li class="nav-item dropdown">
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "profile.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile",  dashboards_dashboard_path, class: "nav-link" %>
              <%= link_to "Log out",  destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>